#######################################################################################################################################
# Using a monthy time series of surface SST and SSS derived from of gridded values derived from the 1948-2018 monthly Sea Temperature 
# and Sea Salinity Profiles from the United Kingdom Met Office EN 4.2.1 Quality Controlled Dataset (Good et al 2013), generated using
# data_download.R, calculated SST and SSS idices outlined in Table 1 of Carter et al. 2020
#######################################################################################################################################
#R Script generated using Microsoft R Open 3.5.1 and run on April 3rd, 2019
require(lubridate)
require(ncdf4)
require(raster)
require(stringr)

local_dir = "~/CEE600M0002_Fall2020/StudentProjectExample" # set to data directory, should match data directory specifiied in data_download.R

#read in monthly gridded SSS/SST netcdf file generated by data_download.R
ss.nc<-nc_open(paste(local_dir, "/raw_data/UKMO4_2_1_analyses_SSS_SST.nc", sep="")) # open connection to .netcdf
sst<-ncvar_get(ss.nc, varid="sst") #extract sea surface temperature variable
sss<-ncvar_get(ss.nc, varid="sss") #extract sea surface salinity variable
lon_o<-ncvar_get(ss.nc, varid="londim") #extract longtidue values
lon<-lon_o-360 #convert to degrees west
lat_o<-ncvar_get(ss.nc, varid="latdim") # extract lagitude values
lat<-rev(lat_o) 
time<-as.Date(ncvar_get(ss.nc, varid="timedim"), origin="1970-01-01 00:00") #extract time values
nc_close(ss.nc) #close .nc connection

sst_cor<-sst[,dim(sst)[2]:1,] #reorder latitude to match extracted coordinates
sss_cor<-sss[,dim(sss)[2]:1,] 

sst_ras<-t(brick(sst_cor, xmn=min(lat), xmx=max(lat), ymn=min(lon),ymx=max(lon))) #convert to raster object time
sss_ras<-t(brick(sss_cor, xmn=min(lat), xmx=max(lat), ymn=min(lon),ymx=max(lon)))

#create shapefiles representing extents for SSS/SST indices outlined in Table 1 of Carter et al. 2020
AWP.ext<-extent(c(-96, -80, 15,28))
WHWP.ext<-extent(c(-145, -80, 15, 28))
TNA.ext<-extent(c( -70, -10,0,30))
NP.ext<-extent(c(-150,-120, 32,55))
NWA.ext<-extent(c(-60,-35,45,55))
ENSO34.ext<-extent(c( -240,-190, -5,5))
TNAss.ext<-extent(c(-80,-30,20,40))
AMO.ext<-extent(c(-80, -0.5, 0, 79))

#extract mean SST over extent defined
AWP_SST<-as.numeric(extract(sst_ras, AWP.ext, fun=mean, na.rm=T))
TNA_SST<-as.numeric(extract(sst_ras, TNA.ext, fun=mean, na.rm=T))
NP_SST<-as.numeric(extract(sst_ras, NP.ext, fun=mean, na.rm=T))
NWA_SST<-as.numeric(extract(sst_ras, NWA.ext, fun=mean, na.rm=T))
ENSO3.4_SST<-as.numeric(extract(sst_ras, ENSO34.ext, fun=mean, na.rm=T))
WHWP_SST<-as.numeric(extract(sst_ras, WHWP.ext, fun=mean, na.rm=T))
AMO_SST<-as.numeric(extract(sst_ras, AMO.ext, fun=mean, na.rm=T))

#calculate SST area indices
sss_ras_awpsubset<-crop(sst_ras, extent(c(-100, -45, 10, 30)))
AWP_SST_area<-rep(NA, times=dim(sst_ras)[3])
for(i in 1:dim(sst_ras)[3]){
	  AWP_SST_area[i]<-length(c(as.matrix(sss_ras_awpsubset[[i]])[c(as.matrix(sss_ras_awpsubset[[i]]))>=273.15+28.5]))
}

sss_ras_whwpsubset<-crop(sst_ras, extent(c(-155, -45, 10, 30)))
WHWP_SST_area<-rep(NA, times=dim(sst_ras)[3])
for(i in 1:dim(sst_ras)[3]){
	  WHWP_SST_area[i]<-length(c(as.matrix(sss_ras_whwpsubset[[i]])[c(as.matrix(sss_ras_whwpsubset[[i]]))>=273.15+28.5]))
}

#extract mean SSS over extent defined
AWP_SSS<-as.numeric(extract(sss_ras, AWP.ext, fun=mean, na.rm=T))
TNA_SSS<-as.numeric(extract(sss_ras, TNAss.ext, fun=mean, na.rm=T))
NP_SSS<-as.numeric(extract(sss_ras, NP.ext, fun=mean, na.rm=T))
time<-as.character(time)

#create processed data directory
if(dir.exists(paste(local_dir, "/training_data", sep=""))){
	  setwd(paste(local_dir, "/training_data", sep=""))
}else{
	  dir.create(paste(local_dir, "/training_data", sep=""))
  setwd(paste(local_dir, "/training_data", sep=""))
}

#create dataset and write to .txt file
write.table(data.frame(time,
                       AWP_SST_area,
                       WHWP_SST_area,
                       AWP_SST, 
                       WHWP_SST,
                       TNA_SST, 
                       NP_SST, 
                       NWA_SST, 
                       ENSO3.4_SST,
                       AMO_SST,
                       TNA_SSS, 
                       AWP_SSS,
                       NP_SSS),
	    row.names=FALSE,
	    SST_SSS_mthly_indices.txt")
rm(list=ls())


